[package]
name = 'movecraft'
version = '1.0.0'

[dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }
AptosTokenObjects = { local = "../../framework/aptos-token-objects" }
AptosStdlib = { local = "../../framework/aptos-stdlib" }

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
movecraft = "_"
