[package]
name = "RMUDGameCoin"
version = "0.0.0"

[addresses]
my_addr = "_"

[dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }
# [dependencies.AptosFramework]
# git = "https://github.com/aptos-labs/aptos-core.git"
# rev = "mainnet"
# subdir = "aptos-move/framework/aptos-framework"
