[package]
name = "music-nft"
version = "1.0.0"
authors = []

[addresses]
movecraft = "0x61b96051f553d767d7e6dfcc04b04c28d793c8af3d07d3a43b4e2f8f4ca04c9f"
my_addr= "_"
[dev-addresses]

[dependencies]
movecraft = { local = "../movecraft" }

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "release-v.1.14"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "release-v.1.14"
subdir = "aptos-move/framework/aptos-stdlib"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "release-v.1.14"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
